Added check for binary feh

diff --git a/install b/install
--- a/install
+++ b/install
@@ -10,14 +10,31 @@ ASSET_DEST="/usr/share/tod_wallpaper/"
 BINARY_SRC="target/release/tod_wallpaper"
 BINARY_DEST="/usr/bin/tod_wallpaper"
 
+## Exit with an error message
+exit_msg() {
+	echo "Command not found '$1' Please install to continue."
+	exit -1
+}
+
+## Check if a binary exists or exit with an error message
+command_or_exit() {
+	command -v $1 >/dev/null 2>&1 || exit_msg $1
+}
+
+## Check for dependencies
+command_or_exit feh
+
+## Try create assets directory
 if [ ! -d $ASSET_DEST ]; then
 	echo Createing $ASSET_DEST
 	mkdir $ASSET_DEST && echo "Done!" || echo "Failed to create directory"
 fi
 
+## Try copy assets
 echo Installing Assets
 cp $ASSET_SRC $ASSET_DEST && echo "Done!" || echo "Failed to copy files"
 
+## Try copy binary
 echo Installing Binary
 if [ -f $BINARY_SRC ]; then
 	cp $BINARY_SRC $BINARY_DEST && echo "Binary installed to /usr/bin/tod_wallpaper" || echo "Failed to copy"
